object form_anotacao: Tform_anotacao
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Nova Anota'#231#227'o'
  ClientHeight = 381
  ClientWidth = 422
  Color = 13619199
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 160
    Top = 8
    Width = 52
    Height = 25
    Alignment = taCenter
    Caption = 'T'#237'tulo'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clYellow
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
  end
  object Label3: TLabel
    Left = 152
    Top = 81
    Width = 86
    Height = 25
    Alignment = taCenter
    Caption = 'Anota'#231#227'o'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clYellow
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    Layout = tlCenter
  end
  object edit_titulo: TEdit
    Left = 24
    Top = 48
    Width = 377
    Height = 29
    Color = 16776176
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clOlive
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
  end
  object btn_salvar: TButton
    Left = 24
    Top = 344
    Width = 377
    Height = 25
    Caption = 'Salvar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clGreen
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    OnClick = btn_salvarClick
  end
  object memo_anotacao: TMemo
    Left = 24
    Top = 120
    Width = 377
    Height = 218
    Color = 16776176
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clTeal
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
  end
end
